# Background and foreground colors
background = #0f0e0b
foreground = #c9c7bf

# Standard colors
palette = 0=#0f0e0b
palette = 1=#b27575
palette = 2=#5a4f38
palette = 3=#bdbd89
palette = 4=#938a5f
palette = 5=#6d6d6d
palette = 6=#345e5e
palette = 7=#C9C1A6

# Bright colors
palette = 8=#9e977e
palette = 9=#d5aeae
palette = 10=#b9dab9
palette = 11=#dfdfc3
palette = 12=#cdcde5
palette = 13=#c482c4
palette = 14=#90cbcb
palette = 15=#c9c7bf
