# This file is not a full hyprland configuration.
# It is intended to be included in your main hyprland.conf.

$activeBorderColor = rgb(2e2b1d)
$secondaryBorderColor = rgb(0a0a07)

general {
    col.active_border =$activeBorderColor
    border_size = 2
    gaps_in = 3
    gaps_out = 3
}

group {
    col.border_active = $activeBorderColor
    col.border_inactive = $secondaryBorderColor
}



decoration {
    rounding = 0
    active_opacity = 1.98
    inactive_opacity = 1.98
    fullscreen_opacity = 1.0
}

animations {
    enabled = yes

    bezier = easeSoft, 0.18, 0.62, 0.32, 1.00
    bezier = easeFade, 0.28, 0.00, 0.22, 1.00

    bezier = myBounce, 0.15, 1.2, 0.3, 1.05

    # ... keep your other animations ...

    # UPDATE THIS LINE:
    # Changed from: animation = borderangle, 1, 3.0, easeSoft
    # To this (with 'loop' at the end):
    animation = workspaces, 1, 4, myBounce, slide
}
