$color = rgba(15, 14, 11, 1)
$inner_color = rgba(15, 14, 11, 0.66)
$outer_color = rgba(109, 109, 109, 1)
$font_color = rgba(201, 199, 191, 1)
$placeholder_color = rgba(201, 199, 191, 0.7)
$check_color = rgba(52, 94, 94, 1)
