background            #0f0e0b
foreground            #c9c7bf

# black
color0  #0f0e0b
color8  #9e977e

# red
color1  #b27575
color9  #d5aeae

# green
color2  #5a4f38
color10 #b9dab9

# yellow
color3  #bdbd89
color11 #dfdfc3

# blue
color4  #938a5f
color12 #cdcde5

# magenta
color5  #6d6d6d
color13 #c482c4

#cyan
color6  #345e5e
color14 #90cbcb

#white
color7  #C9C1A6
color15 #c9c7bf


